### ISSUE TITLE
Latest version does not seem to compile correctly. (Godot 3.0.5 Stable)

### ISSUE THREAD

**Issue by The-Patriach** [kestrelm/Creature_Godot#11]
Hello! 

It gives me an error the likes of...

scons: Reading SConscript files ...
Detected MSVC compiler: x86
Compiled program architecture will be a 32 bit executable. (forcing bits=32).
TypeError: can_build() takes exactly 2 arguments (1 given):
  File "I:\godot-3.0.5-stable\SConstruct", line 407:
    if (config.can_build(selected_platform)):

But when I remove the "creaturegodot" folder, it compiles correctly. I did use the folder that was inside "creaturegodot3".

**Comment by kestrelm** [comment]
Hello, this was addressed here:
https://github.com/kestrelm/Creature_Godot/commit/3a5b028f2bcc98fca68b11a8a46f0df58a8f683b

I just checked and confirmed, it compiles with the latest master of Godot Engine

**Comment by The-Patriach** [comment]
Then there must be something very wrong on my end. 
![godotcomp](https://user-images.githubusercontent.com/28168718/43030040-ecba9b74-8c59-11e8-9f7a-0ed892e06927.PNG) Creature is the only module that I have over. 

Well, then. Thank you very much for checking, still. I appreciate it.

**Comment by kestrelm** [comment]
Hello,
I am on the latest master branch of the godot engine github. I did a full git pull, and a rebuild. Everything built out fine. How about you pull from their master branch instead.
