### ISSUE TITLE
Issue while compiling the Creature Plugin with Godot 3.1

### ISSUE THREAD

**Issue by wermfood** [kestrelm/Creature_Godot#14]
I am having a challenge building the creature plugin for godot using the latest version of Godot 3.1. I can easily compile Godot but when I copy the creaturegodot (from the creaturegodot3 folder) and put it in the modules folder and retry the scons command it always breaks on the godot module with this exception
See below. Can someone give me some guidance on how I can resolve this issue?
* I have pulled the code multiple times with a clean build
* I have updated versions of the IDE to VS 14

<snip>
[ 26%] Compiling ==> modules\creaturegodot\CreatureMetaData.cpp
CreatureMetaData.cpp
D:\godot-master\modules\creaturegodot\glm\detail\type_half.inl: warning C4828: The file contains a character starting at offset 0x72f that is illegal in the current source character set (codepage 65001).
D:\godot-master\modules\creaturegodot\CreatureMetaData.h(46): error C2039: 'shared_ptr': is not a member of 'std'
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\string(19): note: see declaration of 'std'
D:\godot-master\modules\creaturegodot\CreatureMetaData.h(46): error C2065: 'shared_ptr': undeclared identifier
D:\godot-master\modules\creaturegodot\CreatureMetaData.h(46): error C2275: 'CreatureModule::CreatureAnimation': illegal use of this type as an expression
D:\godot-master\modules\creaturegodot\CreatureMetaData.h(46): note: see declaration of 'CreatureModule::CreatureAnimation'
D:\godot-master\modules\creaturegodot\CreatureMetaData.h(46): error C2974: 'std::unordered_map': invalid template argument for '_Ty', type expected
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\unordered_map(76): note: see declaration of 'std::unordered_map'
D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\unordered_map(75): error C3203: 'pair': unspecialized class template can't be used as a template argument for template parameter '_Ty', expected a real type
D:\godot-master\modules\creaturegodot\CreatureMetaData.h(46): error C2143: syntax error: missing ')' before '>'
D:\godot-master\modules\creaturegodot\CreatureMetaData.h(46): error C2059: syntax error: '>'
modules\creaturegodot\CreatureMetaData.cpp(489): error C2511: 'void CreatureModule::CreatureMetaData::updateRegionColors(std::unordered_map<std::string,std::shared_ptr<CreatureModule::CreatureAnimation>,std::hash<_Kty>,std::equal_to<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>> &)': overloaded member function not found in 'CreatureModule::CreatureMetaData'
        with
        [
            _Kty=std::string,
            _Ty=std::shared_ptr<CreatureModule::CreatureAnimation>
        ]
D:\godot-master\modules\creaturegodot\CreatureMetaData.h(21): note: see declaration of 'CreatureModule::CreatureMetaData'
modules\creaturegodot\CreatureMetaData.cpp(496): error C2530: 'clip_regions_data': references must be initialized
modules\creaturegodot\CreatureMetaData.cpp(521): error C2671: 'CreatureModule::CreatureMetaData::updateRegionColors': static member functions do not have 'this' pointers
scons: *** [modules\creaturegodot\CreatureMetaData.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
</snip>

**Comment by kestrelm** [comment]
Hello, 
The error:
'shared_ptr': is not a member of 'std' sounds like you do not have C++11/14 libraries for your compiler? Those are included in the memory header that comes standard with modern C++ compilers. It definitely builds for me, not sure what is going on with your setup.

Thanks

**Comment by wermfood** [comment]
Thanks! I had just updated to the VC 2019 and had to move the includes from version 14.16.27023 to the latest. Once I did that it build fine.
I appreciate the guidance.
