### ISSUE TITLE
Color Flags aren't exported to JSON file

### ISSUE THREAD

**Issue by LemonadeFlashbang** [kestrelm/Creature_Godot#21]
While working on my project, I assembled an animation like the following. I use the r/g/b levels to create a silhouette in some elements, then activate the strike effect. It's an over the top teleport attack. As part of the movement, I fling the character's sleeve/ cloak off their body. In the Creature2D editor, it appears as follows:

![ex](https://user-images.githubusercontent.com/81896582/113500109-50860180-94d0-11eb-8902-4104062eb30c.gif)

That's not how it appears in either my game, or the web player, however. 

The opacity change works- but not the color change. Therefore, the character doesn't become a silhouette- and you can instead see them in all their ugly glory.

![goofus](https://user-images.githubusercontent.com/81896582/113500147-9216ac80-94d0-11eb-9192-14e6ff529a71.PNG)

Here are my export settings:
![image](https://user-images.githubusercontent.com/81896582/113500168-bffbf100-94d0-11eb-89ca-7b7cc9491e90.png)

I've tried by checking "Colors" and "Premultiply Alpha" but had the same results. I also opened up the json file, and can't find any references to red, blue, or green values. The opacity is being recorded fine, however.

![image](https://user-images.githubusercontent.com/81896582/113500195-ea4dae80-94d0-11eb-959b-504d8d798bb7.png)

I am currently on a Pro license, using the Windows version of the tool.

**Comment by kestrelm** [comment]
Hello,
I think support for color animation isn't currently in Godot. For web, if the player supports CreaturePack then colors should be supported. Will investigate and see if it is possible to get this into the Godot Plugin. Thanks

**Comment by LemonadeFlashbang** [comment]
Appreciate the quick response. I'd love it if it could work because I like the effect, but if not I can replace the animation.

**Comment by kestrelm** [comment]
Actually for the Creature JSON format, it looks like metaData support is in there:
https://github.com/kestrelm/Creature_Godot/blob/43155e0550ba8a045831015d522bd42109620dd9/creaturegodot3/creaturegodot/creaturegodot.cpp#L540

This requires the metaData file ( which is also exported in the folder ) to be referenced and then set on the plugin with the call **set_metadata_filename**  : https://github.com/kestrelm/Creature_Godot/blob/43155e0550ba8a045831015d522bd42109620dd9/creaturegodot3/creaturegodot/creaturegodot.cpp#L507

You can give this a go and see if it works?

**Comment by LemonadeFlashbang** [comment]
That worked! I hadn't been using the metadata file since I thought it was just useful for skin swapping. Thank you!
