### ISSUE TITLE
blend_to_animation snaps instead of blending

### ISSUE THREAD

**Issue by azathothgr** [kestrelm/Creature_Godot#3]
Switching to a different animation clip with blend_to_animation is not behaving as expected.

I modified the script in the testPlugin project to the following : 

```
extends CreatureGodot
var counter=0

func _ready():
    # Called every time the node is added to the scene.
    # Initialization here
    set_process(true)
    pass

func _process(delta):
    self.update_animation(delta)
    counter+=1
    if counter==100:
        self.blend_to_animation("default0",0.01)
```

The scene starts with the 'default' animation playing, and should start to blend to the 'default0' animation smoothly after 100 frames, over a time controlled by blend factor, but instead it snaps immediately. Blend factor seems to play no role whatsoever.

**Comment by kestrelm** [comment]
Hello,

Please sync and update your Creature Godot Github. I just checked in a change and tested it locally. Animation blending works in my local test.

Cheers

**Comment by azathothgr** [comment]
Confirmed, works fine now.
