### ISSUE TITLE
Error building Godot 3.0 with creature module

### ISSUE THREAD

**Issue by noidexe** [kestrelm/Creature_Godot#9]
I checked out the 3.0 branch and added the creaturegodot folder to modules/
Compiling goes fine but I'm getting a linking error:
``` 
scons: Reading SConscript files ...
Detected MSVC compiler: amd64
Compiled program architecture will be a 64 bit executable (forcing bits=64).
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
Linking Program        ==> bin\godot.windows.opt.tools.64.exe
   Creando biblioteca bin\godot.windows.opt.tools.64.lib y objeto bin\godot.windows.opt.tools.64.exp
modules.windows.opt.tools.64.lib(creaturegodot.windows.opt.tools.64.obj) : error LNK2019: símbolo externo "public: __cdecl JsonAllocator::~JsonAllocator(void)" (??1JsonAllocator@@QEAA@XZ) sin resolver al que se hace referencia en la función "public: __cdecl CreatureModule::CreatureLoadDataPacket::~CreatureLoadDataPacket(void)" (??1CreatureLoadDataPacket@CreatureModule@@QEAA@XZ)
modules.windows.opt.tools.64.lib(CreatureMetaData.windows.opt.tools.64.obj) : error LNK2001: símbolo externo "public: __cdecl JsonAllocator::~JsonAllocator(void)" (??1JsonAllocator@@QEAA@XZ) sin resolver
modules.windows.opt.tools.64.lib(CreatureModule.windows.opt.tools.64.obj) : error LNK2019: símbolo externo "enum JsonParseStatus __cdecl jsonParse(char *,char * *,union JsonValue *,class JsonAllocator &)" (?jsonParse@@YA?AW4JsonParseStatus@@PEADPEAPEADPEATJsonValue@@AEAVJsonAllocator@@@Z) sin resolver al que se hace referencia en la función "void __cdecl CreatureModule::LoadCreatureJSONData(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class CreatureModule::CreatureLoadDataPacket &)" (?LoadCreatureJSONData@CreatureModule@@YAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVCreatureLoadDataPacket@1@@Z)
modules.windows.opt.tools.64.lib(CreatureMetaData.windows.opt.tools.64.obj) : error LNK2001: símbolo externo "enum JsonParseStatus __cdecl jsonParse(char *,char * *,union JsonValue *,class JsonAllocator &)" (?jsonParse@@YA?AW4JsonParseStatus@@PEADPEAPEADPEATJsonValue@@AEAVJsonAllocator@@@Z) sin resolver
bin\godot.windows.opt.tools.64.exe : fatal error LNK1120: 2 externos sin resolver
scons: building terminated because of errors.
```
(I'll try again at home so I can upload the same error in English)

**Comment by noidexe** [comment]
Tried building from Godot's master branch. Same issue

**Comment by kestrelm** [comment]
Hello,

I just tried a clean build with Godot 3 and the Creature Godot 3 plugin with no issues, everything compiled and linked through correctly.

Here are a list of things to check:

1) Did you get your Creature Godot plugin from this folder: https://github.com/kestrelm/Creature_Godot/tree/master/creaturegodot3/creaturegodot

2) Did you also miss out copying one of the sub-folders? Your linker error indicates that the JSON library was not compiled with it. Did you copy the sub-folder gason in as well?

As I just mentioned, I did a full clean build checked out from this repository and everything ran fine.

Thanks

**Comment by noidexe** [comment]
Those two steps are ok. I didn't try doing a clean build. Will check that now. Thank you

**Comment by kestrelm** [comment]
Hello,
No problem, but I am not sure if a clean build is causing your issue right now.
The error message you posted seems to indicate that you have a linker error with your build with regard to the gason JSON library. I somehow suspect that the provided JSON files are not getting compiled through in your case?

**Comment by Ranoller** [comment]
¿compilas con la opción scons -j? La compilación inicial hay que hacerla con un solo hilo de ejecución.

**Comment by kestrelm** [comment]
@Ranoller This issue has been resolved with the latest merge :) Cheers

**Comment by Ranoller** [comment]
Ok! Good to know!
